### PR TITLE
fix mouse events

### PR DESCRIPTION
**Pull request by TintypeMolly**
Mouse events does not work from time to time

### CODE REVIEW

**Comment by Justineo** [comment]
What do you mean by “from time to time”? We need a minimal reproduction for this.

**Comment by TintypeMolly** [comment]
I'll leave it here when I get to work tomorrow.

**Comment by TintypeMolly** [comment]
vue code
```
<template>
  <vue-echarts
    :options="option"
    @brushselected="onBrushSelected"
    @mouseup="onMouseUp"
  />
</template>

<style>
.echarts {
  width: 100%;
  height: 100%;
}
</style>

<script lang="ts">
import Vue from 'vue';
import moment from 'moment';
import VueEcharts from './VueEcharts.vue';

export default Vue.extend({
  components: {
    VueEcharts,
  },
  props: ['histogram'],
  data() {
    return {
      option: {} // written in JSON bellow
      start: null as moment.Moment | null,
      end: null as moment.Moment | null,
    };
  },
  methods: {
    onMouseUp(event: any) {
      console.log('mouse up', event);
    },
    onBrushSelected(event: any) {
      console.log('brushselected', event);
    },
  },
});
</script>
```

options
```json
{
  "grid": {
    "left": 30,
    "top": 20,
    "right": 10,
    "bottom": 20
  },
  "toolbox": {
    "feature": {
      "brush": {
        "type": [
          "lineX",
          "clear"
        ],
        "title": {
          "lineX": "범위선택",
          "clear": "선택해제"
        }
      }
    }
  },
  "tooltip": {
    "trigger": "axis",
    "axisPointer": {
      "type": "shadow"
    }
  },
  "brush": {
    "xAxisIndex": "all",
    "brushLink": "all",
    "outOfBrush": {
      "colorAlpha": 0.1
    }
  },
  "xAxis": {
    "data": [
      "2019-11-26",
      "2019-11-27",
      "2019-11-28",
      "2019-11-29",
      "2019-11-30",
      "2019-12-01",
      "2019-12-02",
      "2019-12-03"
    ],
    "silent": false,
    "splitLine": {
      "show": false
    },
    "splitArea": {
      "show": false
    }
  },
  "yAxis": {
    "splitArea": {
      "show": false
    },
    "axisTick": {
      "show": false
    }
  },
  "series": [
    {
      "type": "bar",
      "data": [
        72,
        35,
        33,
        25,
        6,
        8,
        26,
        6
      ]
    }
  ],
  "color": [
    "#127ac2"
  ],
  "textStyle": {
    "fontSize": 5
  }
}
```

`@mouseup` and other mouse events do not work from time to time when I use the brush. It's not like it doesn't work at all. It's occasional.

Plugging mouse events directly into the div element, instead of plugging them into event handler of the echart library, fixed my problem. (Maybe it would be the other way around when this pull request is merged, but I haven't found one yet. Echarts has tones of usage after all.)

**Comment by Justineo** [comment]
If you want to attach event handlers to the root `<div>` element, just use the `.native` modifier (`@mouseup.native="..."`). This library only exposes events coming from ECharts itself.

**Pull request closed without merging**
