### PR TITLE
feat: add chart init event

### PR DESCRIPTION
**Pull request by yugasun**
- [x] Update rollup config, add rollup,cross-env devDependencies
- [x] Add chart init event

Because for some projects, we need use the echart instances object, so I have to emit the instance init event, and add the `chart` params for outer using.

### CODE REVIEW

**Comment by Justineo** [comment]
Hi, thanks for contributing. Can you provide a use case for this?

**Comment by yugasun** [comment]
For example, in my project all chart containers are resizable, and the initial width/height are configured by server api, so after I load the api data, I need resize all chart container by [echartsInstance.resize()](http://echarts.baidu.com/api.html#echartsInstance.resize) . So I need listen on the init event, and emit `echartsInstance` for outer use, even though you may tell me to use `this.$refs.scatter.chart.resize()` like below:

```js
<chart
     ref="scatter"
      :options="scatter"
      :init-options="initOptions"
      auto-resize
    />
```

but you know [vm.$refs](https://vuejs.org/v2/api/#ref) may come more later, below is the official docs said:

> An important note about the ref registration timing: because the refs themselves are created as a result of the render function, you cannot access them on the initial render - they don’t exist yet! $refs is also non-reactive, therefore you should not attempt to use it in templates for data-binding.

For these reasons, I need listen the `echartsInstance` init event.

> Sorry, I can not show out company private codes.

**Comment by Justineo** [comment]
You can try setting the chart's `width` & `height` to `100%` in CSS and use `auto-resize` prop.

**Comment by yugasun** [comment]
I have set `auto-resize` prop for all chart components, because when chart container DOM init, the width and height is unknow or not suitable, even  can not adjust suitable.

**Comment by Justineo** [comment]
Charts with `auto-resize` should run `resize()` on every time the root element got resized. If you have set `width` and `height` to `100%` they should be able to resize automatically.

**Comment by yugasun** [comment]
@Justineo any new ideas?

**Comment by jojoyuji** [comment]
same issue here...

Any comments/ideas @Justineo ?

**Comment by Justineo** [comment]
By releasing a new version of `resize-detector`, this shouldn't be an issue anymore. Plz update to `vue-echarts@3.0.9` to try out (actually it's already working as expected in @yugasun's [earlier fiddle](https://jsfiddle.net/yugasun/zh60tjvw/)). Thanks.

**Pull request closed without merging**
